routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) {
        if(Auth::user()->role() == 'admin') {
            return redirect(route('admin.index'));
        }
        else if(Auth::user()->role() == 'owner') {
            return redirect(route('owner.index'));
        }
    }
    return view('auth.login');
});

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', 'ProfileController');
});

Route::group(['middleware' => ['auth', 'admin']], function () {
//    Route::resource('admin', 'AdminController');
    Route::resource('admin', 'AdminDashboardController');
    Route::resource('event', 'EventController');
    Route::resource('tourist', 'TouristController');
    Route::resource('hotline', 'HotlineController');
    Route::resource('resort', 'ResortController');
    Route::resource('archive', 'ArchiveController');
});

Route::group(['middleware' => ['auth', 'owner']], function () {
    Route::resource('owner', 'OwnerController');
    Route::resource('rates', 'RateController');
//    Route::resource('resort', 'ResortController');
    Route::resource('upload', 'ImageController');
});

Route::resource('view', 'ViewController');

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

use App\Amenity;
use App\Baranggay;
use App\Image;
use App\Rate;
use App\Resort;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OwnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::user()->id;

        $resort = Resort::query()
            ->where('user_id','=', $user_id)
            ->get();


        foreach ($resort as $json) {
            $json['category'] = explode(',',$json['category']);
        }

        foreach ($resort as $json) {
            $json['amenity'] = explode(',',$json['amenity']);
        }

        $locations = Baranggay::all();



        return view('owner.dashboard.index',
            [
                'resort' => json_decode($resort) ? $resort : '',
                'view' => $resort ? $resort : '',
                'locations' => $locations ? $locations : '',
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user_id = Auth::user()->id;

        $this->validate($request, [
            'title'         => 'required',
            'location'      => 'required',
            'category'      => 'required'
        ]);

        $category = '';

        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }

        $insert = Resort::create([
            'title'         => $request->title,
            'user_id'       => $user_id,
            'description'   => $request->description,
            'location'      => $request->location,
            'category'      => rtrim($category,','),
            'amenity'       => ''
        ]);

        session()->flash('message', 'Successfully Added!!');

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $user_id = Auth::user()->id;
        $resort = Resort::find($request->id);
        $category = '';
        $amenity = '';
//        dd($request->id);die;
        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }
        foreach ($request->amenity as $ame) {
            $amenity = $amenity.''.$ame.',';
        }
        $resort->title              = $request->title;
        $resort->location           = $request->location;
        $resort->category           = rtrim($category,',');
        $resort->amenity            = rtrim($amenity,',');
        $resort->description        = $request->description;
        $resort->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('owner.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail = Resort::find($id);
        return $detail;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $resort = Resort::find($request->id);
        $category = '';
        $amenity = '';
//        dd($request->amenity);die;
        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }
        foreach ($request->$amenity as $ame) {
            $amenity = $amenity.''.$ame.',';
        }

        $resort->title              = $request->title;
        $resort->location           = $request->location;
        $resort->category           = rtrim($category,',');
        $resort->amenity            = rtrim($amenity,',');
        $resort->description        = $request->description;
        $resort->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('owner.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/owner/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Samaletsgo</title>

    <!-- Fontfaces CSS-->
    <link href="{{ asset('css/font-face.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/font-awesome-4.7/css/font-awesome.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/font-awesome-5/css/fontawesome-all.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/mdi-font/css/material-design-iconic-font.min.css') }}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{{ asset('vendor/bootstrap-4.1/bootstrap.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">

    <!-- Vendor CSS-->
    <link href="{{ asset('vendor/animsition/animsition.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/wow/animate.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/css-hamburgers/hamburgers.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/slick/slick.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/select2/select2.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('vendor/perfect-scrollbar/perfect-scrollbar.css') }}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{ asset('css/theme.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" media="all">

</head>

<body class="animsition">
<div class="page-wrapper">
    <!-- HEADER DESKTOP-->
    <header class="header-desktop3 d-none d-lg-block">
        <div class="section__content section__content--p35">
            <div class="header3-wrap">
                <div class="header__logo">
                    <a href="{{ route('owner.index') }}">
                        {{--<img src="{{ asset('images/samal-logo.PNG') }}" alt="CoolAdmin" width="40%" />--}}
                        <h3 style="color: #ffffff; margin-left: 10px;">SAMALETSGO</h3>
                    </a>
                </div>
                <div class="header__navbar">
                    <ul class="list-unstyled">
                        {{--<li>--}}
                            {{--<a href="{{ route('admin.index') }}">--}}
                                {{--<i class="fas fa-tachometer-alt"></i>Dashboard--}}
                                {{--<span class="bot-line"></span>--}}
                            {{--</a>--}}
                        {{--</li>--}}
                        {{--<li>--}}
                            {{--<a href="{{ route('event.index') }}">--}}
                                {{--<i class="fas fa-calendar-o"></i>--}}
                                {{--<span class="bot-line"></span>Events--}}
                            {{--</a>--}}
                        {{--</li>--}}
                        {{--<li>--}}
                            {{--<a href="{{ route('tourist.index') }}">--}}
                                {{--<i class="fas fa-camera-retro"></i>--}}
                                {{--<span class="bot-line"></span>Tourist Spots--}}
                            {{--</a>--}}
                        {{--</li>--}}
                        {{--<li>--}}
                            {{--<a href="{{ route('resort.index') }}">--}}
                                {{--<i class="fas fa-umbrella"></i>--}}
                                {{--<span class="bot-line"></span>Resorts</a>--}}
                        {{--</li>--}}
                        {{--<li>--}}
                            {{--<a href="{{ route('hotline.index') }}">--}}
                                {{--<i class="fas fa-phone"></i>--}}
                                {{--<span class="bot-line"></span>Hotlines</a>--}}
                        {{--</li>--}}
                    </ul>
                </div>
                <div class="header__tool">
                    <div class="account-wrap">
                        <div class="account-item account-item--style2 clearfix js-item-menu">
                            <div class="image">
                                <img src="{{ asset('images/avatar.png') }}" alt="Profile" />
                            </div>
                            <div class="content">
                                <a class="js-acc-btn" href="#">{{ Auth::user()->name }}</a>
                            </div>
                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    <div class="image">
                                        <a href="#">
                                            <img src="{{ asset('images/avatar.png') }}" alt="Profile" />
                                        </a>
                                    </div>
                                    <div class="content">
                                        <h5 class="name">
                                            <a href="#">{{ Auth::user()->name }}</a>
                                        </h5>
                                        <span class="email">{{ Auth::user()->email }}</span>
                                    </div>
                                </div>
                                <div class="account-dropdown__body">
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-account"></i>Account</a>
                                    </div>
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-settings"></i>Setting</a>
                                    </div>
                                    <div class="account-dropdown__item">
                                        <a href="{{ route('archive.index') }}">
                                            <i class="zmdi zmdi-archive"></i>Archive</a>
                                    </div>
                                </div>
                                <div class="account-dropdown__footer">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            <i class="zmdi zmdi-power"></i>{{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" hidden action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </li>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- END HEADER DESKTOP-->

    <!-- HEADER MOBILE-->
    <header class="header-mobile header-mobile-2 d-block d-lg-none">
        <div class="header-mobile__bar">
            <div class="container-fluid">
                <div class="header-mobile-inner">
                    <a class="logo" href="index.html">
                        <img src="images/icon/logo-white.png" alt="CoolAdmin" />
                    </a>
                    <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>

    </header>
    <div class="sub-header-mobile-2 d-block d-lg-none">
        <div class="header__tool">
            <div class="account-wrap">
                <div class="account-item account-item--style2 clearfix js-item-menu">
                    <div class="image">
                        <img src="#" alt="Profile" />
                    </div>
                    <div class="content">
                        <a class="js-acc-btn" href="#">{{ Auth::user()->name }}</a>
                    </div>
                    <div class="account-dropdown js-dropdown">
                        <div class="info clearfix">
                            <div class="image">
                                <a href="#">
                                    <img src="#" alt="Profile" />
                                </a>
                            </div>
                            <div class="content">
                                <h5 class="name">
                                    <a href="#">{{ Auth::user()->name }}</a>
                                </h5>
                                <span class="email">{{ Auth::user()->email }}</span>
                            </div>
                        </div>
                        <div class="account-dropdown__body">
                            <div class="account-dropdown__item">
                                <a href="#">
                                    <i class="zmdi zmdi-account"></i>Account</a>
                            </div>
                            <div class="account-dropdown__item">
                                <a href="#">
                                    <i class="zmdi zmdi-settings"></i>Setting</a>
                            </div>
                        </div>
                        <div class="account-dropdown__footer">
                            <a href="#">
                                <i class="zmdi zmdi-power"></i>Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END HEADER MOBILE -->

    <!-- PAGE CONTENT-->
    <div class="page-content--bgf7">

        @yield('content')

        <!-- COPYRIGHT-->
        <section class="p-t-60 p-b-20">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                            <p>Copyright © 2018 Samaletsgo. All rights reserved. Template by <a href="#">Samaletsgo</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END COPYRIGHT-->
    </div>

</div>

<!-- Jquery JS-->
<script src="{{ asset('vendor/jquery-3.2.1.min.js') }}"></script>
<!-- Bootstrap JS-->
<script src="{{ asset('vendor/bootstrap-4.1/popper.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap-4.1/bootstrap.min.js') }}"></script>
<!-- Vendor JS       -->
<script src="{{ asset('vendor/slick/slick.min.js') }}">
</script>
<script src="{{ asset('vendor/wow/wow.min.js') }}"></script>
<script src="{{ asset('vendor/animsition/animsition.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap-progressbar/bootstrap-progressbar.min.js') }}">
</script>
<script src="{{ asset('vendor/counter-up/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('vendor/counter-up/jquery.counterup.min.js') }}">
</script>
<script src="{{ asset('vendor/circle-progress/circle-progress.min.js') }}"></script>
<script src="{{ asset('vendor/perfect-scrollbar/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('vendor/chartjs/Chart.bundle.min.js') }}"></script>
<script src="{{ asset('vendor/select2/select2.min.js') }}"></script>
<script src="{{ asset('js/jquery.dataTables.min.js') }}" type="text/javascript" charset="utf8"></script>
<script src="{{ asset('js/dataTables.bootstrap4.min.js') }}" type="text/javascript" charset="utf8"></script>

<!-- Main JS-->
<script src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('js/numericFormat.js') }}"></script>

<!-- JS -->
@yield('javascript')

</body>

</html>
<!-- end document-->