routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) {
        if(Auth::user()->role() == 'admin') {
            return redirect(route('admin.index'));
        }
        else if(Auth::user()->role() == 'owner') {
            return redirect(route('owner.index'));
        }
    }
    return view('auth.login');
});

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', 'ProfileController');
});

Route::group(['middleware' => ['auth', 'admin']], function () {
//    Route::resource('admin', 'AdminController');
    Route::resource('admin', 'AdminDashboardController');
    Route::resource('event', 'EventController');
    Route::resource('tourist', 'TouristController');
    Route::resource('hotline', 'HotlineController');
    Route::resource('resort', 'ResortController');
    Route::resource('archive', 'ArchiveController');
});

Route::group(['middleware' => ['auth', 'owner']], function () {
    Route::resource('owner', 'OwnerController');
    Route::resource('rates', 'RateController');
//    Route::resource('resort', 'ResortController');
    Route::resource('upload', 'ImageController');
});

Route::resource('view', 'ViewController');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $users = User::orderBy('updated_at', 'desc')->paginate(10);
//        return view('admin.dashboard.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.auth.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'role' => 'required|string',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
        User::create([
            'name' => $request['name'],
            'role' => $request['role'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);

        session()->flash('message', 'Successfully Added!!');

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

use App\Amenity;
use App\Baranggay;
use App\Image;
use App\Rate;
use App\Resort;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OwnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::user()->id;

        $resort = Resort::query()
            ->where('user_id','=', $user_id)
            ->get();


        foreach ($resort as $json) {
            $json['category'] = explode(',',$json['category']);
        }

        foreach ($resort as $json) {
            $json['amenity'] = explode(',',$json['amenity']);
        }

        $locations = Baranggay::all();



        return view('owner.dashboard.index',
            [
                'resort' => json_decode($resort) ? $resort : '',
                'view' => $resort ? $resort : '',
                'locations' => $locations ? $locations : '',
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user_id = Auth::user()->id;

        $this->validate($request, [
            'title'         => 'required',
            'location'      => 'required',
            'category'      => 'required'
        ]);

        $category = '';

        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }

        $insert = Resort::create([
            'title'         => $request->title,
            'user_id'       => $user_id,
            'description'   => $request->description,
            'location'      => $request->location,
            'category'      => rtrim($category,','),
            'amenity'       => ''
        ]);

        session()->flash('message', 'Successfully Added!!');

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $user_id = Auth::user()->id;
        $resort = Resort::find($request->id);
        $category = '';
        $amenity = '';
//        dd($request->id);die;
        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }
        foreach ($request->amenity as $ame) {
            $amenity = $amenity.''.$ame.',';
        }
        $resort->title              = $request->title;
        $resort->location           = $request->location;
        $resort->category           = rtrim($category,',');
        $resort->amenity            = rtrim($amenity,',');
        $resort->description        = $request->description;
        $resort->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('owner.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail = Resort::find($id);
        return $detail;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $resort = Resort::find($request->id);
        $category = '';
        $amenity = '';
//        dd($request->amenity);die;
        foreach ($request->category as $cat) {
            $category = $category.''.$cat.',';
        }
        foreach ($request->$amenity as $ame) {
            $amenity = $amenity.''.$ame.',';
        }

        $resort->title              = $request->title;
        $resort->location           = $request->location;
        $resort->category           = rtrim($category,',');
        $resort->amenity            = rtrim($amenity,',');
        $resort->description        = $request->description;
        $resort->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('owner.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/owner/dashboard/setting.blade.php
@extends('owner.layout.app')

@section('content')

    <!-- STATISTIC-->
    <section class="statistic statistic2">
        <div class="container">
            <div class="row">
                <div class="col-3">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title mb-3">Settings</strong>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    Page Info
                                </div>
                                <div class="col-4">
                                    <button class="btn btn-secondary btn-sm pull-right" id="btn_pageinfo">
                                        <i class="fa fa-cog"></i>
                                    </button>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col">
                                    Amenities
                                </div>
                                <div class="col-4">
                                    <button class="btn btn-secondary btn-sm pull-right" id="btn_amenities">
                                        <i class="fa fa-cog"></i>
                                    </button>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col">
                                    Rates
                                </div>
                                <div class="col-4">
                                    <button class="btn btn-secondary btn-sm pull-right" id="btn_rates">
                                        <i class="fa fa-cog"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Page info -->
                <div class="col">
                    <div class="card " id="card_pageinfo">
                        <div class="card-header">
                            <strong class="card-title mb-3">
                                <i class="fa fa-cog"></i> Page Info
                            </strong>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5>GENERAL</h5>
                                    <hr>
                                    <div class="row">
                                        <div class="col-2">
                                            <label>Title</label>
                                        </div>
                                        <div class="col">
                                            <form action="" method="post" id="form_title">
                                                @csrf
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="title" placeholder="Title">
                                                </div>
                                                <button class="btn btn-success btn-sm" type="submit">Save Changes</button>
                                                <a href="#form_title" class="">Cancel</a>
                                            </form>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-2">
                                            <label>Description</label>
                                        </div>
                                        <div class="col">
                                            <form action="" method="post" id="form_desc">
                                                @csrf
                                                <div class="form-group">
                                                    <textarea class="form-control" rows="5" placeholder="Description" name="description"></textarea>
                                                </div>
                                                <button class="btn btn-success btn-sm" type="submit">Save Changes</button>
                                                <a href="#form_desc" class="">Cancel</a>
                                            </form>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-2">
                                            <label>Category</label>
                                        </div>
                                        <div class="col">
                                            <form action="" method="post">
                                                <div class="form-group">
                                                    <div class="checkbox">
                                                        <label for="category1" class="form-check-label ">
                                                            <input type="checkbox" id="category1" name="category[]" value="Beach" class="form-check-input"> Beach
                                                        </label>
                                                    </div>
                                                    <div class="checkbox">
                                                        <label for="category2" class="form-check-label ">
                                                            <input type="checkbox" id="category2" name="category[]" value="Pool" class="form-check-input"> Pool
                                                        </label>
                                                    </div>
                                                </div>
                                                {{--<button class="btn btn-success btn-sm" type="submit">Save Changes</button>--}}
                                                {{--<a href="#form_title" class="">Cancel</a>--}}
                                            </form>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-2">
                                            <label>Image</label>
                                        </div>
                                        <div class="col">
                                            <form method="post" action="{{ route('upload.store') }}" enctype="multipart/form-data" id="form_image">
                                                @csrf
                                                <div class="form-group">
                                                    <input type="file" class="form-control" name="images[]" multiple/>
                                                    <input type="hidden" name="resort_id" value=""/>
                                                </div>
                                                <button class="btn btn-success btn-sm" type="submit">Save Changes</button>
                                                <a href="#form_image" class="">Cancel</a>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end page info -->

                    <!-- Amenities -->
                    <div class="card " id="card_amenities">
                        <div class="card-header">
                            <strong class="card-title mb-3">
                                <i class="fa fa-cog"></i> Amenities
                            </strong>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end amenities -->

                    <!-- Rates -->
                    <div class="card " id="card_rates">
                        <div class="card-header">
                            <strong class="card-title mb-3">
                                <i class="fa fa-cog"></i> Rates
                            </strong>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end Rates -->


                </div>
            </div>
        </div>
    </section>
    <!-- END STATISTIC-->


@endsection

@section('javascript')
    <script>
        $(document).ready( function () {
            $('#accountTable').DataTable();
        } );
        let page = $('#card_pageinfo');
        let rate = $('#card_rates');
        let amenity = $('#card_amenities');

        function showSettings() {

        }

        $("#btn_pageinfo").on('click', function () {
            $(page).removeClass('hide-card');//toggle this
            $(amenity).addClass('hide-card');
            $(rate).addClass('hide-card');
        });

        $("#btn_amenities").on('click', function () {
            $(page).addClass('hide-card');
            $(amenity).removeClass('hide-card');//add this
            $(rate).addClass('hide-card');
        });

        $("#btn_rates").on('click', function () {
            $(page).addClass('hide-card');
            $(amenity).addClass('hide-card');
            $(rate).removeClass('hide-card');//add this
        });
    </script>
@stop